---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app_name }}
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30002