image:
  repository: jacknely/gateway
  tag: latest
  pullPolicy: Always

name: gateway
domain: nel.so
host: gateway

env:
  APPLICATION_STAGE: prod

container:
  port: 8000

ports:
  http:
    port: 8000
    targetPort: 8000
    nodePort: 30006

service:
  type: NodePort

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}