name: Build and Publish

on:
  release:
    types: [published]
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push:
    name: Build Docker image and push to repositories 
    runs-on: ubuntu-latest
    env:
      IMAGE: jacknely/gateway
    
    if: GitHub.ref == 'refs/heads/main' || GitHub.event_name == 'release'
    steps:
        - name: Generate build ID
          id: prep
          run: |
              branch=${GITHUB_REF##*/}
              sha=${GITHUB_SHA::8}
              ts=$(date +%s)
              echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}" 
  
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build image and push to Docker Hub
          uses: docker/build-push-action@v2
          with:
            context: .
            push: ${{ GitHub.event_name != 'release' }}
            tags: ${{ github.event.release.tag_name }}

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}