name: Build and Publish

on:
  release:
    types: [created]

jobs:
  build-and-release:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    env:
      IMAGE: jacknely/gateway
    
    if: GitHub.ref == 'refs/heads/main' || GitHub.event_name == 'release'
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        - name: Build image and push to Docker Hub
          uses: docker/build-push-action@v2
          with:
            context: .
            push: ${{ GitHub.event_name != 'pull_request' }}
            tags: ${{ env.IMAGE }}:latest  #, ${{ env.IMAGE }}:${{ github.ref }}

        - name: Test
          run: |
            echo ${{ github.event.release.tag_name }}

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}